wpa_project/contact_us/urls.py
from django.urls import path
from .views import *
app_name = 'contact_us'
urlpatterns = [
    path('category/<int:category_id>/', CategoryView.as_view(), name='category'),
    path('category/', CategoryView.as_view(), name='category'),
    path('category_list/', CategoryListView.as_view(), name='category_list'),
    path('complaint/', ComplaintView.as_view(), name='complaint'),
    path('complaint/<int:pk>/', ComplaintView.as_view(), name='complaint'),
    path('complaint_list/', ComplaintListView.as_view(), name='complaint_list'),
    path('contact/', MessageView.as_view(), name='contact'),
    path('contact/<int:message_id>/', MessageView.as_view(), name='contact'),
    path('delete_category/<int:category_id>/', CategoryDeleteView.as_view(), name='delete_category'),
    path('message_list/', MessageListView.as_view(), name='message_list'),
    path('message_list/<int:spam>/', MessageListView.as_view(), name='message_list'),
    path('thanks/', ThanksView.as_view(), name='thanks'),
    path('thanks/<str:arg>/', ThanksView.as_view(), name='thanks')
]

wpa_project/info/urls.py
from django.urls import path
from .views import *
app_name = 'info'

urlpatterns = [
    path('announcement_form/', AnnouncementFormView.as_view(), name='announcement_form'),
    path('announcement_form/<int:pk>', AnnouncementFormView.as_view(), name='announcement_form'),
    path('announcement_list/', AnnouncementList.as_view(), name='announcement_list'),
    path('category/', CategoryView.as_view(), name='category'),
    path('category/<int:category_id>/', CategoryView.as_view(), name='category'),
    path('category_delete/<int:category_id>/', CategoryDeleteView.as_view(), name='category_delete'),
    path('category_list/', CategoryListView.as_view(), name='category_list'),
    path('faq', FaqList.as_view(), name='faq'),
    path('info/<str:info>/', InfoView.as_view(), name='info'),
    path('edit/', FaqFormView.as_view(), name='edit'),
    path('edit/<int:faq_id>/', FaqFormView.as_view(), name='edit'),
    path('policy/', PolicyFormView.as_view(), name='policy'),
    path('policy/<int:policy>/', PolicyFormView.as_view(), name='policy'),
    path('policy/<int:policy>/<int:version>/', PolicyFormView.as_view(), name='policy'),
    path('policy_list', PolicyListView.as_view(), name='policy_list'),
    path('staff_list/', StaffList.as_view(), name='staff_list'),
    path('staff_profile_form/', StaffProfileFormView.as_view(), name='staff_profile_form'),
    path('staff_profile_form/<int:pk>/', StaffProfileFormView.as_view(), name='staff_profile_form'),
]

wpa_project/payment/urls.py
from django.urls import path
from .views import *
app_name = 'payment'
urlpatterns = [
    path('card_default/<int:card_id>/', CardDefaultView.as_view(), name='card_default'),
    path('card_manage/', CardManageView.as_view(), name='card_manage'),
    path('card_remove/', CardRemoveView.as_view(), name='card_remove'),
    path('card_remove/<int:card_id>/', CardRemoveView.as_view(), name='card_remove'),
    path('collections/', CollectionView.as_view(), name='collections'),
    path('collections/<int:pk>/', CollectionView.as_view(), name='collections'),
    path('make_payment/', CreatePaymentView.as_view(), name='make_payment'),
    path('reimbursement_form/', ReimbursementFormView.as_view(), name='reimbursement_form'),
    path('reimbursement_form/<int:pk>/', ReimbursementFormView.as_view(), name='reimbursement_form'),
    path('reimbursement_list/', ReimbursementListView.as_view(), name='reimbursement_list'),
    path('reimbursement_vote/<int:pk>/', ReimbursementVoteView.as_view(), name='reimbursement_vote'),
    path('report', ReportView.as_view(), name='report'),
    path('view_payment/<pk>/', PaymentView.as_view(), name='view_payment'),
]

wpa_project/program_app/urls.py
from django.urls import path
from .views import *
app_name = 'programs'
urlpatterns = [
    path('admit_wait/<int:event>/', AdmitWaitView.as_view(), name='admit_wait'),
    path('admit_wait/<int:event>/<int:family_id>/', AdmitWaitView.as_view(), name='admit_wait'),
    path('beginner_class/<int:beginner_class>/', BeginnerClassView.as_view(), name='beginner_class'),
    path('beginner_class/', BeginnerClassView.as_view(), name='beginner_class'),
    path('calendar/', CalendarView.as_view(), name='calendar'),
    path('calendar/<int:year>/<int:month>/', CalendarView.as_view(), name='calendar'),
    path('class_list/<int:past>/', BeginnerClassListView.as_view(), name='class_list'),
    path('class_list/', BeginnerClassListView.as_view(), name='class_list'),
    path('class_registration_admin/<int:family_id>/', ClassRegistrationAdminView.as_view(), name='class_registration_admin'),
    path('class_registration_admin_list/', AdminRegistrationListView.as_view(), name='class_registration_admin_list'),
    path('class_registration/<int:event>/', ClassRegistrationView.as_view(), name='class_registration'),
    path('class_registration/', ClassRegistrationView.as_view(), name='class_registration'),
    path('class_sign_in/<int:reg_id>/', ClassSignInView.as_view(), name='class_sign_in'),
    path('class_status/<str:class_id>/', ClassStatusView.as_view(), name='class_status'),
    path('class_status/', ClassStatusView.as_view(), name='class_status'),
    path('google_calendar/', EventCalendarView.as_view(), name='google_calendar'),
    path('history/', HistoryView.as_view(), name='history'),
    path('history/<int:family_id>/', HistoryView.as_view(), name='history'),
    path('resume_registration/<int:reg_id>/', ResumeRegistrationView.as_view(), name='resume_registration'),
    path('send_email/', SendEmailView.as_view(), name='send_email'),
    path('send_email/<int:beginner_class>/', SendEmailView.as_view(), name='send_email'),
    path('staff_attendance/', StaffReportView.as_view(), name='staff_attendance'),
    path('staff_point_hisotry/<int:student>/', StaffPointHistoryView.as_view(), name='staff_point_history'),
    path('wait_list/<int:event>/', WaitListView.as_view(), name='wait_list'),
]

wpa_project/student_app/urls.py
from django.urls import path
from .views import *
app_name = 'registration'
urlpatterns = [
        path('', IndexView.as_view(), name='index'),
        path('add_student/<int:student_id>/', AddStudentView.as_view(), name='add_student'),
        path('add_student/', AddStudentView.as_view(), name='add_student'),
        path('delete_student/<int:pk>/', StudentDeleteView.as_view(), name='delete_student'),
        path('delete_student_family/<int:pk>/', StudentFamilyDeleteView.as_view(), name='delete_student_family'),
        path('instructor_update/', InstructorUpdateView.as_view(), name='instructor_update'),
        path('is_joad/<int:student_id>/', StudentIsJoadView.as_view(), name='is_joad'),
        path('login/', LoginView.as_view(), name='login'),
        path('pdf/<int:student_id>/', PdfGetView.as_view(), name='pdf'),
        path('profile/', ProfileView.as_view(), name='profile'),
        path('recaptcha/', RecaptchaView.as_view(), name='recaptcha'),
        path('search/', SearchEmailView.as_view(), name='search'),
        path('search_name/', SearchNameView.as_view(), name='search_name'),
        path('search_phone/', SearchPhoneView.as_view(), name='search_phone'),
        path('search_result/', SearchResultView.as_view(), name='search_result'),
        path('search_result/<int:student_family>/', SearchResultView.as_view(), name='search_result'),
        path('search_result_list/', SearchResultListView.as_view(), name='search_result_list'),
        path('send_email/', SendEmailView.as_view(), name='send_email'),
        path('student_family/<int:family_id>/', StudentFamilyView.as_view(), name='student_family'),
        path('student_family/', StudentFamilyView.as_view(), name='student_family'),
        path('student_list/', StudentList.as_view(), name='student_list'),
        path('student_table/', StudentTableView.as_view(), name='student_table'),
        path('theme/', ThemeView.as_view(), name='theme'),
        path('update_user/<int:user_id>/', UserView.as_view(), name='update_user'),
        path('waiver/<int:student_id>/', WaiverView.as_view(), name='waiver'),
        path('waiver_recreate/<int:student_id>/', WaiverRecreateView.as_view(), name='waiver_recreate')
]

wpa_project/wpa_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from student_app.views import SignupView

urlpatterns = [
    path('', include('student_app.urls', namespace='registration')),
    path('accounts/signup/', SignupView.as_view(), name="account_signup"),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('contact_us/', include('contact_us.urls', namespace='contact_us')),
    path('events/', include('event.urls', namespace='events')),
    path('facebook/', include('facebook.urls', namespace='facebook')),
    path('information/', include('info.urls', namespace='information')),
    path('inventory/', include('inventory.urls', namespace='inventory')),
    path('joad/', include('joad.urls', namespace='joad')),
    path('membership/', include('membership.urls', namespace='membership')),
    path('minutes/', include('minutes.urls', namespace='minutes')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('programs/', include('program_app.urls', namespace='programs')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wpa_project/student_app/forms/instructor_form.py
from django.forms import ModelForm, SelectDateWidget
from django.conf import settings
from django.apps import apps
from django.utils import timezone


class InstructorForm(ModelForm):

    class Meta:
        model = apps.get_model(settings.AUTH_USER_MODEL)
        fields = ('instructor_expire_date', 'instructor_level')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['instructor_expire_date'].widget = SelectDateWidget(
            years=range(timezone.datetime.today().year, timezone.datetime.today().year + 4, 1))
        self.fields['instructor_level'].widget.attrs.update({'placeholder': 'Level'})

wpa_project/student_app/forms/recaptcha_form.py
import requests
from django.forms import Form, CharField, URLField, HiddenInput
from django.conf import settings

import logging
logger = logging.getLogger(__name__)


class RecaptchaForm(Form): # pragma: no cover
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['captcha'] = CharField(widget=HiddenInput)
        self.fields['url'] = CharField(widget=HiddenInput)

    def get_score(self, remote_ip):
        data = {"secret": settings.RECAPTCHA_SECRET_KEY_V3, "response": self.cleaned_data['captcha']}
        if remote_ip is not None:
            data['remoteip'] = remote_ip
        try:
            response = requests.post('https://www.google.com/recaptcha/api/siteverify', data=data)
            response_data = response.json()
            if response_data['success']:
                return response_data['score']
            else:
                return None
        except (requests.ConnectionError, requests.RequestException, requests.Timeout, requests.TooManyRedirects):
            return 0

wpa_project/student_app/forms/send_email_form.py
from django import forms
from django.utils import timezone
from ..models import Student, User
from ..src import EmailMessage

import logging
logger = logging.getLogger(__name__)


class SendEmailForm(forms.Form):

    def __init__(self, *args, **kwargs):
        is_super = False
        if 'is_super' in kwargs:
            is_super = kwargs.get('is_super', False)
            kwargs.pop('is_super')
        super().__init__(*args, **kwargs)
        choices = [('board', 'Board'), ('staff', 'Staff'), ('current members', 'Current Members'), ('joad', 'JOAD')]
        if is_super:
            # choices.append(('all members', 'All Members'))
            choices.append(('students', 'Students that have attended'))
        self.fields['include_days'] = forms.IntegerField(max_value=1000, min_value=0, initial=90, required=False)
        self.fields['recipients'] = forms.MultipleChoiceField(choices=choices, widget=forms.CheckboxSelectMultiple())
        self.fields['subject'] = forms.CharField(initial='Message from Woodley Park Archers')
        self.fields['subject'].widget.attrs.update({'class': 'form-control m-2'})
        self.fields['message'] = forms.CharField(widget=forms.Textarea)
        self.fields['message'].widget.attrs.update({'cols': 60, 'rows': 8, 'class': 'form-control m-2'})

wpa_project/student_app/views/class_available_view.py
import logging
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.http import  HttpResponseForbidden
from django.views.generic.base import View
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from ..forms import CostsForm
from ..models import BeginnerClass
from ..src import ClassRegistrationHelper
logger = logging.getLogger(__name__)


class ClassAvailableView(LoginRequiredMixin, View):
    def get(self, request, class_id):
        bc = BeginnerClass.objects.get(pk=class_id)
        ec = ClassRegistrationHelper().enrolled_count(bc)
        return JsonResponse({'beginner': bc.beginner_limit - ec['beginner'],
                             'returnee': bc.returnee_limit - ec['returnee']})

wpa_project/student_app/views/index_view.py
from django.shortcuts import reverse
from django.utils import timezone
from facebook.views import PostList
from allauth.account.forms import LoginForm

from info.models import Announcement
import logging
logger = logging.getLogger(__name__)


class IndexView(PostList):
    template_name = 'student_app/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = LoginForm()
        context['signup_url'] = reverse('account_signup')
        context['announcements'] = Announcement.objects.filter(
            status=1,
            end_date__gte=timezone.now(),
            begin_date__lte=timezone.now()
        )
        return context

wpa_project/student_app/views/instructor_update_view.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.edit import FormView

import logging
from django.http import JsonResponse

from ..forms import InstructorForm
logger = logging.getLogger(__name__)


class InstructorUpdateView(PermissionRequiredMixin, FormView):
    form_class = InstructorForm
    template_name = 'student_app/forms/instructor.html'
    permission_required = 'student_app.instructors'

    def form_invalid(self, form):
        logging.warning(form.errors)
        return JsonResponse({'status': "error"})

    def form_valid(self, form):
        self.request.user.instructor_expire_date = form.cleaned_data.get('instructor_expire_date',
                                                                         self.request.user.instructor_expire_date)
        self.request.user.instructor_level = form.cleaned_data.get('instructor_level',
                                                                   self.request.user.instructor_level)
        self.request.user.save()
        return JsonResponse({
            'status': 'SUCCESS',
            'expire_date': self.request.user.instructor_expire_date,
            'level': self.request.user.instructor_level
        })

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['instance'] = self.request.user
        return kwargs

wpa_project/student_app/views/login_view.py
from allauth.account.views import LoginView


class LoginView(LoginView):
    template_name = 'account/login_insert.html'

wpa_project/student_app/views/pdf_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404
from django_sendfile import sendfile

# Create your views here.
from django.views import View
from ..models import Student


class PdfGetView(LoginRequiredMixin, View):
    def get(self, request, student_id, thumb=False):
        if request.user.has_perm('student_app.board'):
            student = get_object_or_404(Student, id=student_id)
        else:
            sf = get_object_or_404(Student, user=request.user).student_family
            student = get_object_or_404(Student, id=student_id, student_family=sf)

        if student.signature_pdf:
            return sendfile(request, student.signature_pdf.path)

        return HttpResponseForbidden()

wpa_project/student_app/views/profile_view.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateView

from ..forms import ThemeForm

import logging
logger = logging.getLogger(__name__)


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'student_app/profile.html'
    """Shows the users profile"""

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['this_student'] = self.request.user.student_set.last()
        context['theme_form'] = ThemeForm(initial={'theme': self.request.session.get('theme', 'browser')})
        context['student_family'] = None
        if context['this_student'] is not None:
            context['student_family'] = context['this_student'].student_family
        if context['student_family'] is not None:
            context['students'] = context['student_family'].student_set.all()
        return context

wpa_project/student_app/templates/429.html
{% extends "base.html" %}

{% block main %}
<h1>Too Many Requests</h1>

<p>You are sending too many requests.</p>
{% endblock %}

wpa_project/student_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        {% load static %}
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
              crossorigin="anonymous">


        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/jquery.cookie-consent/dist/jquery.cookie-consent.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
                integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
                crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
                integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
                crossorigin="anonymous"></script>
        <script src="https://www.google.com/recaptcha/api.js?onload=recaptchaCallback&render={{RECAPTCHA_SITE_KEY_V3}}" async defer></script>

        <script src="{% static 'js/main.js' %}"></script>
        <script nonce="{{CSP_NONCE}}">
            let url_theme = "{% url 'registration:theme' %}";
            let theme = "{{request.session.theme}}";
            let recaptcha_site_v3 = "{{RECAPTCHA_SITE_KEY_V3}}";
            let url_recaptcha = "{% url 'registration:recaptcha' %}";
            let recaptcha_url_list = [
                "{% url 'information:info' 'about' %}",
                "{% url 'information:info' 'directions' %}",
                "{% url 'information:info' 'class_description' %}",
                "{% url 'contact_us:contact' %}",
                "{% url 'payment:make_payment' %}",
                "{% url 'information:faq' %}",
                "{% url 'information:info' 'terms' %}",
                "{% url 'information:info' 'privacy' %}",
                "{% url 'information:info' 'covid' %}",
                "{% url 'information:info' 'constitution' %}",
                "{% url 'information:info' 'by-laws' %}",
                "{% url 'joad:index'%}",
                "{% url 'programs:calendar' %}",
                "{% url 'programs:google_calendar' %}",
                "{% url 'account_logout' %}",
                "{% url 'registration:profile' %}"
                ];
        </script>
        <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        {% block script %}{% endblock %}

        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <a href="/">
            <img class="banner-img" alt="Woodley Park Archers" 
                src="{% static 'images/WPAHeader4.jpg' %}" title="Woodley Park Archers">
        </a>
        {% include "nav.html" %}        
        <div>
            <input type="hidden" id="alert-message" value="{{ alert_message }}">
            <div id="messages-container">
                    {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
            </div>
            <div class="main-content-block">
                <div id="block-main" class="{{request.session.theme|default:'browser'}}-theme">
                    {% block main %}{% endblock %}
                </div>
                <div>
                    {% block right %}{% endblock %}
                    <form id="recaptcha-form" method="post" action="{% url 'registration:recaptcha' %}">{% csrf_token %}
                        {{ recaptcha_form.captcha }}
                        {{ recaptcha_form.url }}
                    </form>
                </div>

            </div>
        </div>

        <div class="modal" id="alert-warning">
          <div class="modal-dialog">
            <div class="modal-content">

              <!-- Modal Header -->
            <div class="modal-header">
              <h4 id="alert-title" class="modal-title"></h4>
              <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
            </div>

            <!-- Modal body -->
            <div class="modal-body" id="div-warning">
            </div>

            <!-- Modal footer -->
            <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
            </div>

            </div>
          </div>
        </div>

        <footer class="small text-center text-muted">

        </footer>
        {% block end_script %}
        {% endblock %}
    </body>
</html>