wpa_project/info/urls.py
from django.urls import path
from .views import *
app_name = 'info'

urlpatterns = [
    path('announcement_form/', AnnouncementFormView.as_view(), name='announcement_form'),
    path('announcement_form/<int:pk>', AnnouncementFormView.as_view(), name='announcement_form'),
    path('announcement_list/', AnnouncementList.as_view(), name='announcement_list'),
    path('category/', CategoryView.as_view(), name='category'),
    path('category/<int:category_id>/', CategoryView.as_view(), name='category'),
    path('category_delete/<int:category_id>/', CategoryDeleteView.as_view(), name='category_delete'),
    path('category_list/', CategoryListView.as_view(), name='category_list'),
    path('faq', FaqList.as_view(), name='faq'),
    path('info/<str:info>/', InfoView.as_view(), name='info'),
    path('edit/', FaqFormView.as_view(), name='edit'),
    path('edit/<int:faq_id>/', FaqFormView.as_view(), name='edit'),
    path('policy/', PolicyFormView.as_view(), name='policy'),
    path('policy/<int:policy>/', PolicyFormView.as_view(), name='policy'),
    path('policy/<int:policy>/<int:version>/', PolicyFormView.as_view(), name='policy'),
    path('policy_list', PolicyListView.as_view(), name='policy_list'),
    path('staff_list/', StaffList.as_view(), name='staff_list'),
    path('staff_profile_form/', StaffProfileFormView.as_view(), name='staff_profile_form'),
    path('staff_profile_form/<int:pk>/', StaffProfileFormView.as_view(), name='staff_profile_form'),
]

wpa_project/student_app/urls.py
from django.urls import path
from .views import *
app_name = 'registration'
urlpatterns = [
        path('', IndexView.as_view(), name='index'),
        path('add_student/<int:student_id>/', AddStudentView.as_view(), name='add_student'),
        path('add_student/', AddStudentView.as_view(), name='add_student'),
        path('delete_student/<int:pk>/', StudentDeleteView.as_view(), name='delete_student'),
        path('delete_student_family/<int:pk>/', StudentFamilyDeleteView.as_view(), name='delete_student_family'),
        path('instructor_update/', InstructorUpdateView.as_view(), name='instructor_update'),
        path('is_joad/<int:student_id>/', StudentIsJoadView.as_view(), name='is_joad'),
        path('login/', LoginView.as_view(), name='login'),
        path('pdf/<int:student_id>/', PdfGetView.as_view(), name='pdf'),
        path('profile/', ProfileView.as_view(), name='profile'),
        path('recaptcha/', RecaptchaView.as_view(), name='recaptcha'),
        path('search/', SearchEmailView.as_view(), name='search'),
        path('search_name/', SearchNameView.as_view(), name='search_name'),
        path('search_phone/', SearchPhoneView.as_view(), name='search_phone'),
        path('search_result/', SearchResultView.as_view(), name='search_result'),
        path('search_result/<int:student_family>/', SearchResultView.as_view(), name='search_result'),
        path('search_result_list/', SearchResultListView.as_view(), name='search_result_list'),
        path('send_email/', SendEmailView.as_view(), name='send_email'),
        path('student_family/<int:family_id>/', StudentFamilyView.as_view(), name='student_family'),
        path('student_family/', StudentFamilyView.as_view(), name='student_family'),
        path('student_list/', StudentList.as_view(), name='student_list'),
        path('student_table/', StudentTableView.as_view(), name='student_table'),
        path('theme/', ThemeView.as_view(), name='theme'),
        path('update_user/<int:user_id>/', UserView.as_view(), name='update_user'),
        path('waiver/<int:student_id>/', WaiverView.as_view(), name='waiver'),
        path('waiver_recreate/<int:student_id>/', WaiverRecreateView.as_view(), name='waiver_recreate')
]

wpa_project/wpa_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from student_app.views import SignupView

urlpatterns = [
    path('', include('student_app.urls', namespace='registration')),
    path('accounts/signup/', SignupView.as_view(), name="account_signup"),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('contact_us/', include('contact_us.urls', namespace='contact_us')),
    path('events/', include('event.urls', namespace='events')),
    path('facebook/', include('facebook.urls', namespace='facebook')),
    path('information/', include('info.urls', namespace='information')),
    path('inventory/', include('inventory.urls', namespace='inventory')),
    path('joad/', include('joad.urls', namespace='joad')),
    path('membership/', include('membership.urls', namespace='membership')),
    path('minutes/', include('minutes.urls', namespace='minutes')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('programs/', include('program_app.urls', namespace='programs')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wpa_project/student_app/models/student.py
import logging
from django.db import models
from django.conf import settings
from django.apps import apps

from .student_family import StudentFamily

from django.utils import timezone
logger = logging.getLogger(__name__)


class Student(models.Model):
    student_family = models.ForeignKey(StudentFamily, on_delete=models.SET_NULL, null=True, default=None)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, default=None)

    # user fields
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    dob = models.DateField()
    email = models.EmailField(null=True, default=None, unique=True)

    # hidden fields
    safety_class = models.DateField(null=True)
    covid_vax = models.BooleanField(default=False)
    signature = models.ImageField(upload_to="signatures/%Y/%m/%d/", null=True)
    signature_pdf = models.FileField(upload_to="signatures/%Y/%m/%d/", null=True)
    is_joad = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_user(self):
        User = apps.get_model('student_app', 'User')
        if self.user is None:
            return User.objects.filter(student__student_family=self.student_family)
        else:
            users = User.objects.filter(id=self.user.id)
        return users

wpa_project/student_app/models/student_family.py
import logging

from django.db import models

from django.utils import timezone
from ..fields import PhoneField
logger = logging.getLogger(__name__)


class StudentFamily(models.Model):
    # user fields
    street = models.CharField(max_length=150)
    city = models.CharField(max_length=150)
    state = models.CharField(max_length=3)
    post_code = models.CharField(max_length=10)
    phone = PhoneField(max_length=20)

    # hidden fields
    registration_date = models.DateField(default=timezone.now)

wpa_project/contact_us/forms/category_form.py
from django.forms import BooleanField, CheckboxInput

from src.model_form import MyModelForm
from ..models import Category


class CategoryForm(MyModelForm):

    class Meta(MyModelForm.Meta):
        model = Category
        required_fields = ['title', 'email', 'is_public']
        optional_fields = []
        fields = optional_fields + required_fields

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['is_public'] = BooleanField(
            widget=CheckboxInput(attrs={'class': "m-2"}),
            required=False,
            initial=False)

wpa_project/contact_us/forms/complaint_form.py
import logging
from django.conf import settings
from django.utils import timezone
from django.forms import BooleanField, CheckboxInput, SelectDateWidget
from src.model_form import MyModelForm
from ..models import Complaint, ComplaintComment
from student_app.models import User
logger = logging.getLogger(__name__)


class ComplaintForm(MyModelForm):

    class Meta(MyModelForm.Meta):
        model = Complaint
        required_fields = ['category', 'incident_date', 'message']
        optional_fields = []
        fields = optional_fields + required_fields

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['incident_date'].required = False
        self.fields['incident_date'].label = 'Incident Date (optional)'
        self.fields['incident_date'].widget = SelectDateWidget(
            years=range(timezone.datetime.today().year, timezone.datetime.today().year - 2, -1))
        self.fields['incident_date'].widget.attrs.update({'class': 'm-2'})
        self.fields['anonymous'] = BooleanField(
            widget=CheckboxInput(attrs={'class': "m-2"}),
            required=False,
            initial=False,
            label='I wish to make an anonymous complaint')
        self.fields['category'].label += ' (only harassment complaints can be submitted anonymously)'
        self.fields['resolved'] = BooleanField(
            widget=CheckboxInput(attrs={'class': "m-2"}),
            required=False,
            initial=False,
            label='This complaint has been resolved')
        if self.instance.id:
            for f in ['category', 'incident_date', 'message', 'anonymous']:
                self.fields[f].disabled = True
            if self.instance.resolved_date is not None:
                self.fields['resolved'].initial = True


class ComplaintCommentForm(MyModelForm):
    class Meta(MyModelForm.Meta):
        model = ComplaintComment
        required_fields = ['comment']
        hidden_fields = ['complaint', 'user']
        read_fields = ['comment_date',]
        fields = required_fields + hidden_fields + read_fields

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        logger.warning(self.initial)
        self.fields['complaint'].label = ""
        self.fields['comment_date'].initial = ''
        if self.instance.user:
            self.fields['comment'].disabled = True
            self.student = self.instance.user.student_set.last()
        else:
            self.student = self.initial.get('student', None)
        self.fields['comment'].widget.attrs.update({'cols': 80, 'rows': 3})

    def clean(self):
        cleaned_data = super().clean()
        if self.instance.id is None:
            if len(cleaned_data['comment']):
                cleaned_data['comment_date'] = timezone.now()
        return cleaned_data

wpa_project/contact_us/forms/message_form.py
import logging
from src.model_form import MyModelForm
from ..models import Message
logger = logging.getLogger(__name__)


class MessageForm(MyModelForm):

    class Meta(MyModelForm.Meta):
        model = Message
        required_fields = ['contact_name', 'email', 'category', 'message', 'spam_category']
        optional_fields = []
        fields = optional_fields + required_fields

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        self.can_submit = True
        super().__init__(*args, **kwargs)
        logging.debug(self.instance)
        if not self.user.is_authenticated:
            self.fields.pop('spam_category')
        elif not self.user.is_board:
            self.fields.pop('spam_category')

        self.has_instance = self.instance.id is None
        logging.debug(self.has_instance)
        if not self.has_instance:
            logging.debug(self.fields)
            for f in self.fields:
                self.fields[f].required = False
                self.fields[f].widget.attrs.update({'class': 'form-control m-2'})
        self.fields['category'].queryset = self.fields['category'].queryset.filter(is_public=True)

wpa_project/event/forms/award_form.py
import math
import random
from django import forms
from django.utils import timezone

from ..models import VolunteerAward
import logging

logger = logging.getLogger(__name__)


class AwardForm(forms.ModelForm):
    class Meta:
        model = VolunteerAward
        required_fields = ['events', 'award']
        optional_fields = ['received', 'student', 'description']
        fields = optional_fields + required_fields

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for f in self.Meta.optional_fields:
            self.fields[f].required = False
        if self.instance.id:
            self.fields['student'].disabled = True
            self.fields['events'].disabled = True
        else:
            self.fields['student'].widget = forms.HiddenInput()
        self.fields['student'].label = 'Volunteer'

        self.fields['events'].queryset = self.fields['events'].queryset.filter(
            event_date__lte=timezone.now(),
            event_date__gte=(timezone.now() - timezone.timedelta(days=90))).order_by('-event_date')
        self.fields['events'].widget.attrs['size'] = 12

    def clean(self):
        cleaned_data = super().clean()
        logger.warning(cleaned_data)
        if cleaned_data['student'] is None:

            student_list = []
            for event in cleaned_data['events']:
                for record in event.volunteerrecord_set.all():
                    points = math.floor(record.volunteer_points)
                    for n in range(points):
                        if not record.student.user.has_perm('student_app.board'):
                            student_list.append(record.student)
            logger.warning(student_list)
            if len(student_list):
                cleaned_data['student'] = random.choice(student_list)
            else:
                self.add_error('events', 'No eligible volunteers for this event')

wpa_project/event/forms/cancel_form.py
from django import forms

from src.model_form import MyModelForm
from payment.models import PaymentErrorLog
from ..models import Registration
import logging

logger = logging.getLogger(__name__)


class CancelForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['donate'] = forms.BooleanField(
            widget=forms.CheckboxInput(attrs={'class': "m-2"}),
            required=False,
            initial=False,
            label='I wish to donate my refund')


class CancelSetForm(MyModelForm):
    class Meta(MyModelForm.Meta):
        model = Registration
        required_fields = ['student']
        optional_fields = []
        fields = optional_fields + required_fields

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['student'].widget = forms.HiddenInput()

        cancel_attrs = {'class': "m-2 cancel-check"}
        if self.instance.pay_status in ['cancel_pending', 'refunded']:
            cancel_attrs['disabled'] = 'disabled'
        self.fields['cancel'] = forms.BooleanField(
            widget=forms.CheckboxInput(attrs=cancel_attrs),
            required=False,
            initial=False,
            label='Cancel')

        amount = 0
        # if self.instance.student.member_set.filter():

        if self.instance.pay_status == 'paid' and not (self.instance.student.user and self.instance.student.user.has_perm('student_app.staff')):
            amount = self.instance.event.cost_standard
            # TODO add member price if member when registered.
        self.pay_status = self.instance.pay_status
        if self.pay_status == 'start':
            self.pay_status = 'Unsuccessful'
        elif self.pay_status == 'wait error':
            payment_error = PaymentErrorLog.objects.filter(idempotency_key=self.instance.idempotency_key).last()
            self.pay_status = 'Error'
            if payment_error:
                self.pay_status += f": {payment_error.error_code.replace('_', ' ').title()}"

        self.fields['amount'] = forms.IntegerField(
            widget=forms.HiddenInput(attrs={'class': "cancel-amount"}),
            initial=amount,
            required=False
        )

        self.empty_permitted = False

wpa_project/event/forms/volunteer_event_form.py
from django import forms
from django.utils import timezone

from src.model_form import MyModelForm
from ..models import Event, VolunteerEvent
from src.model_helper import choices
import logging

logger = logging.getLogger(__name__)


class VolunteerEventForm(MyModelForm):

    class Meta(MyModelForm.Meta):
        model = VolunteerEvent
        required_fields = ['volunteer_limit', 'description']
        optional_fields = []
        fields = optional_fields + required_fields

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        d = timezone.now()
        d = timezone.now().replace(year=d.year, month=d.month, day=d.day, hour=16, minute=0, second=0)
        self.fields['event_date'] = forms.DateTimeField(initial=d)
        self.fields['state'] = forms.ChoiceField(choices=choices(Event.event_states))
        self.fields['cancel_message'] = forms.CharField(required=False)
        self.fields['volunteer_points'] = forms.IntegerField(initial=0)
        if self.instance.id:
            self.fields['event_date'].initial = self.instance.event.event_date
            self.fields['state'].initial = self.instance.event.state

wpa_project/facebook/forms/post_form.py
from django import forms
from django.utils import timezone
from ..models import EmbeddedPosts
import logging

logger = logging.getLogger(__name__)


class PostForm(forms.ModelForm):
    class Meta:
        model = EmbeddedPosts
        fields = ['begin_date', 'end_date', 'is_event', 'content']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for f in ['begin_date', 'end_date', 'is_event']:
            self.fields[f].required = False
        d = timezone.now()
        self.fields['end_date'].initial = d.replace(year=d.year + 1)

wpa_project/student_app/templates/student_app/forms/instructor.html
<form class="col form" method="post" autocomplete="off" id="instructor_form">
    {% csrf_token %}
    <div class="row">
        <div class="col-1"></div>
        <div class="col">
            <table class="table table-bordered">
                <tbody>
                    <tr>
                        <td>USAA Archery Instructor Certificate Expiration Date:</td>
                        <td>Level</td>
                        <td rowspan="2">
                            <button id="btn-update-instructor" class="btn btn-primary m-3" onsubmit="update_instructor()">
                                Update
                            </button>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            {{ form.instructor_expire_date }}
                            {% for error in form.instructor_expire_date.errors %}
                                <p class="help-block">{{ error }}</p>
                            {% endfor %}
                        </td>
                        <td>
                            {{ form.instructor_level }}
                            {% for error in form.instructor_level.errors %}
                                <p class="help-block">{{ error }}</p>
                            {% endfor %}
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-1"></div>
    </div>
</form>

wpa_project/student_app/templates/student_app/forms/student.html
<form class="form border p-2 col" method="post" action="{% url 'registration:add_student' %}" autocomplete="off" id="student_form">
    {% csrf_token %}
    <div class="row mr-2">
        <div class="d-md-inline-flex">
            <div class="form-floating input-group-md m-2">
                {{ form.first_name }}
                <label for="id_first_name">
                    <span style="color:Black;">{{ form.first_name.label }}</span>
                </label>
                {% for error in form.first_name.errors %}
                    <p class="help-block">{{ error }}</p>
                {% endfor %}
            </div>
            <div class="form-floating input-group-md m-2">
                {{ form.last_name }}
                <label for="id_last_name">
                    <span style="color:Black;">{{ form.last_name.label }}</span>
                </label>
                {% for error in form.last_name.errors %}
                    <p class="help-block">{{ error }}</p>
                {% endfor %}
            </div>
            <div class="form-floating input-group-md m-2">
                <p>{{ form.dob.label }}</p>
                <p>{{ form.dob }}</p>
                <p>
                    {% for error in form.dob.errors %}
                        <p class="help-block">{{ error }}</p>
                    {% endfor %}
                </p>
                <div id="dob-error" class="row text-danger"></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="flex-column">
            {% if not student.is_user %}
                <div class="m-2 ms-3">
                    If you add an email below we will email them asking them to join, and they will be associated with this account.
                </div>
            {% endif %}

            <div class="input-group-md m-2">
                {{ form.email }}
                {% for error in form.email.errors %}
                    <p class="help-block">{{ error }}</p>
                {% endfor %}
            </div>
            <div class="col-2 m-2 d-flex align-items-center">
                {% if student.this_user %}
                    <a href="{% url 'account_email' %}">Edit Email</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% if perms.student_app.staff %}
        <div class="d-flex flex-row px-3 input-group input-group-md">
            <div class="col-2">
                {{ form.safety_class.label }}
            </div>
            <div class="col">
                {{ form.safety_class }}
                {% for error in form.safety_class.errors %}
                    <p class="help-block">{{ error }}</p>
                {% endfor %}
            </div>

            {% if student.joad_age  or student.staff %}
            <div class="m-2">
                <input type="checkbox" class="m-2 is-joad-check"
                    joad_url="{% url 'registration:is_joad' student.id %}"  id="joad_check_{{ student.id }}"
                            {% if student.is_joad %} checked="checked" {% endif %}>
                    Joad {% if student.staff %}Staff {% else %}Student {% endif %}
            </div>
            {% endif %}
            <div>
                {% if student.id %}
                    <a class="nav-link" href="{% url 'registration:waiver' student.id %}">
                        {% if student.signature %}
                            Update Signature
                        {% else %}
                            Signature Required
                        {% endif %}
                    </a>
                {% endif %}
            </div>
        </div>

        {% if perms.student_app.board and student.is_user %}
        <div class="d-flex flex-row px-3 input-group input-group-md">
            <div class="m-2">{{user_form.is_staff}} {{user_form.is_staff.label}}</div>
            <div class="m-2">{{user_form.is_board}} {{user_form.is_board.label}}</div>
            <div class="m-2">{{user_form.is_instructor}} {{user_form.is_instructor.label}}</div>
            <div class="m-2">{{user_form.instructor_expire_date}} {{user_form.instructor_expire_date.label}}</div>
            {% if user.is_superuser %}
                <div class="m-2">{{user_form.is_active}} {{user_form.is_active.label}}</div>
            {% endif %}
        </div>
        {% endif %}

    {% endif %}

    <div class="flex-row m-2">
        <button id="btn-student-form-add" class="btn btn-primary" type="submit">Add</button>
        <button id="btn-student-form-close" class="btn btn-primary">Close</button>
        {% if student.id and not student.this_user %}
            <a class="btn btn-danger" href="{% url 'registration:delete_student' student.id%}">Delete</a>
        {% endif %}
    </div>
</form>

wpa_project/student_app/templates/student_app/forms/student_family_form.html
<form id="family-form" method="post" action="{% url 'registration:student_family' %}" autocomplete="off" class="form">
{% csrf_token %}
    <div class="row">
        <div class="flex-column">
            <div class="form-floating input-group-md m-2">
                {{ form.street }}
                <label for="id_street">
                    <span style="color:Black;">{{ form.street.label }}</span>
                </label>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="d-md-inline-flex">
            <div class="form-floating input-group-md m-2 flex-grow-1">
                {{ form.city }}
                <label for="id_city">
                    <span style="color:Black;">{{ form.city.label }}</span>
                </label>
            </div>
            <div class="form-floating input-group-md m-2">
                {{ form.state }}
                <label for="id_state">
                    <span style="color:Black;">{{ form.state.label }}</span>
                </label>
            </div>
            <div class="form-floating input-group-md m-2">
                {{ form.post_code }}
                <label for="id_post_code">
                    <span style="color:Black;">{{ form.post_code.label }}</span>
                </label>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="d-md-inline-flex">
            <div class="form-floating input-group-md m-2">
                {{ form.phone }}
                <label for="id_phone">
                    <span style="color:Black;">{{ form.phone.label }}</span>
                </label>
            </div>
        </div>
    </div>
    <div class="flex-row px-2 m-2">
        <button id="btn-family-form" class="btn btn-primary" type="submit">Update</button>
    </div>
</form>