wpa_project/event/urls.py
from django.urls import path
from .views import *
app_name = 'events'
urlpatterns = [
    path('cancel/', CancelView.as_view(), name='cancel'),
    path('cancel/<int:student_family>/', CancelView.as_view(), name='cancel'),
    path('event_attend/<int:registration>/', EventAttendView.as_view(), name='event_attend'),
    path('event_attend_list/<int:event>/', EventAttendListView.as_view(), name='event_attend_list'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('registration/<int:event>/', RegistrationView.as_view(), name='registration'),
    path('volunteer_award/', VolunteerAwardView.as_view(), name='volunteer_award'),
    path('volunteer_award/<int:pk>/', VolunteerAwardView.as_view(), name='volunteer_award'),
    path('volunteer_award_info/', VolunteerAwardInfoView.as_view(), name='volunteer_award_info'),
    path('volunteer_award_list/', VolunteerAwardListView.as_view(), name='volunteer_award_list'),
    path('volunteer_event/', VolunteerEventView.as_view(), name='volunteer_event'),
    path('volunteer_event/<int:event>/', VolunteerEventView.as_view(), name='volunteer_event'),
    path('volunteer_event_list/', VolunteerEventListView.as_view(), name='volunteer_event_list'),
    path('volunteer_event_list/<int:past>/', VolunteerEventListView.as_view(), name='volunteer_event_list'),
    path('volunteer_record/', VolunteerRecordView.as_view(), name='volunteer_record'),
]

wpa_project/info/urls.py
from django.urls import path
from .views import *
app_name = 'info'

urlpatterns = [
    path('announcement_form/', AnnouncementFormView.as_view(), name='announcement_form'),
    path('announcement_form/<int:pk>', AnnouncementFormView.as_view(), name='announcement_form'),
    path('announcement_list/', AnnouncementList.as_view(), name='announcement_list'),
    path('category/', CategoryView.as_view(), name='category'),
    path('category/<int:category_id>/', CategoryView.as_view(), name='category'),
    path('category_delete/<int:category_id>/', CategoryDeleteView.as_view(), name='category_delete'),
    path('category_list/', CategoryListView.as_view(), name='category_list'),
    path('faq', FaqList.as_view(), name='faq'),
    path('info/<str:info>/', InfoView.as_view(), name='info'),
    path('edit/', FaqFormView.as_view(), name='edit'),
    path('edit/<int:faq_id>/', FaqFormView.as_view(), name='edit'),
    path('policy/', PolicyFormView.as_view(), name='policy'),
    path('policy/<int:policy>/', PolicyFormView.as_view(), name='policy'),
    path('policy/<int:policy>/<int:version>/', PolicyFormView.as_view(), name='policy'),
    path('policy_list', PolicyListView.as_view(), name='policy_list'),
    path('staff_list/', StaffList.as_view(), name='staff_list'),
    path('staff_profile_form/', StaffProfileFormView.as_view(), name='staff_profile_form'),
    path('staff_profile_form/<int:pk>/', StaffProfileFormView.as_view(), name='staff_profile_form'),
]

wpa_project/membership/urls.py
from django.urls import path
from .views import *
app_name = 'membership'
urlpatterns = [
    path('level/<int:level_id>/', LevelView.as_view(), name='level'),
    path('level/', LevelView.as_view(), name='level'),
    path('election/', ElectionView.as_view(), name='election'),
    path('election/<int:election_id>/', ElectionView.as_view(), name='election'),
    path('election_list/', ElectionListView.as_view(), name='election_list'),
    path('election_result/<int:election_id>/', ElectionResultView.as_view(), name='election_result'),
    path('election_vote/<int:election_id>/', ElectionVoteView.as_view(), name='election_vote'),
    path('member_list/', MemberList.as_view(), name='member_list'),
    path('membership/', MembershipView.as_view(), name='membership'),
    path('membership/<int:sf_id>/', MembershipView.as_view(), name='membership'),
]

wpa_project/payment/urls.py
from django.urls import path
from .views import *
app_name = 'payment'
urlpatterns = [
    path('card_default/<int:card_id>/', CardDefaultView.as_view(), name='card_default'),
    path('card_manage/', CardManageView.as_view(), name='card_manage'),
    path('card_remove/', CardRemoveView.as_view(), name='card_remove'),
    path('card_remove/<int:card_id>/', CardRemoveView.as_view(), name='card_remove'),
    path('collections/', CollectionView.as_view(), name='collections'),
    path('collections/<int:pk>/', CollectionView.as_view(), name='collections'),
    path('make_payment/', CreatePaymentView.as_view(), name='make_payment'),
    path('reimbursement_form/', ReimbursementFormView.as_view(), name='reimbursement_form'),
    path('reimbursement_form/<int:pk>/', ReimbursementFormView.as_view(), name='reimbursement_form'),
    path('reimbursement_list/', ReimbursementListView.as_view(), name='reimbursement_list'),
    path('reimbursement_vote/<int:pk>/', ReimbursementVoteView.as_view(), name='reimbursement_vote'),
    path('report', ReportView.as_view(), name='report'),
    path('view_payment/<pk>/', PaymentView.as_view(), name='view_payment'),
]

wpa_project/program_app/urls.py
from django.urls import path
from .views import *
app_name = 'programs'
urlpatterns = [
    path('admit_wait/<int:event>/', AdmitWaitView.as_view(), name='admit_wait'),
    path('admit_wait/<int:event>/<int:family_id>/', AdmitWaitView.as_view(), name='admit_wait'),
    path('beginner_class/<int:beginner_class>/', BeginnerClassView.as_view(), name='beginner_class'),
    path('beginner_class/', BeginnerClassView.as_view(), name='beginner_class'),
    path('calendar/', CalendarView.as_view(), name='calendar'),
    path('calendar/<int:year>/<int:month>/', CalendarView.as_view(), name='calendar'),
    path('class_list/<int:past>/', BeginnerClassListView.as_view(), name='class_list'),
    path('class_list/', BeginnerClassListView.as_view(), name='class_list'),
    path('class_registration_admin/<int:family_id>/', ClassRegistrationAdminView.as_view(), name='class_registration_admin'),
    path('class_registration_admin_list/', AdminRegistrationListView.as_view(), name='class_registration_admin_list'),
    path('class_registration/<int:event>/', ClassRegistrationView.as_view(), name='class_registration'),
    path('class_registration/', ClassRegistrationView.as_view(), name='class_registration'),
    path('class_sign_in/<int:reg_id>/', ClassSignInView.as_view(), name='class_sign_in'),
    path('class_status/<str:class_id>/', ClassStatusView.as_view(), name='class_status'),
    path('class_status/', ClassStatusView.as_view(), name='class_status'),
    path('google_calendar/', EventCalendarView.as_view(), name='google_calendar'),
    path('history/', HistoryView.as_view(), name='history'),
    path('history/<int:family_id>/', HistoryView.as_view(), name='history'),
    path('resume_registration/<int:reg_id>/', ResumeRegistrationView.as_view(), name='resume_registration'),
    path('send_email/', SendEmailView.as_view(), name='send_email'),
    path('send_email/<int:beginner_class>/', SendEmailView.as_view(), name='send_email'),
    path('staff_attendance/', StaffReportView.as_view(), name='staff_attendance'),
    path('staff_point_hisotry/<int:student>/', StaffPointHistoryView.as_view(), name='staff_point_history'),
    path('wait_list/<int:event>/', WaitListView.as_view(), name='wait_list'),
]

wpa_project/student_app/urls.py
from django.urls import path
from .views import *
app_name = 'registration'
urlpatterns = [
        path('', IndexView.as_view(), name='index'),
        path('add_student/<int:student_id>/', AddStudentView.as_view(), name='add_student'),
        path('add_student/', AddStudentView.as_view(), name='add_student'),
        path('delete_student/<int:pk>/', StudentDeleteView.as_view(), name='delete_student'),
        path('delete_student_family/<int:pk>/', StudentFamilyDeleteView.as_view(), name='delete_student_family'),
        path('instructor_update/', InstructorUpdateView.as_view(), name='instructor_update'),
        path('is_joad/<int:student_id>/', StudentIsJoadView.as_view(), name='is_joad'),
        path('login/', LoginView.as_view(), name='login'),
        path('pdf/<int:student_id>/', PdfGetView.as_view(), name='pdf'),
        path('profile/', ProfileView.as_view(), name='profile'),
        path('recaptcha/', RecaptchaView.as_view(), name='recaptcha'),
        path('search/', SearchEmailView.as_view(), name='search'),
        path('search_name/', SearchNameView.as_view(), name='search_name'),
        path('search_phone/', SearchPhoneView.as_view(), name='search_phone'),
        path('search_result/', SearchResultView.as_view(), name='search_result'),
        path('search_result/<int:student_family>/', SearchResultView.as_view(), name='search_result'),
        path('search_result_list/', SearchResultListView.as_view(), name='search_result_list'),
        path('send_email/', SendEmailView.as_view(), name='send_email'),
        path('student_family/<int:family_id>/', StudentFamilyView.as_view(), name='student_family'),
        path('student_family/', StudentFamilyView.as_view(), name='student_family'),
        path('student_list/', StudentList.as_view(), name='student_list'),
        path('student_table/', StudentTableView.as_view(), name='student_table'),
        path('theme/', ThemeView.as_view(), name='theme'),
        path('update_user/<int:user_id>/', UserView.as_view(), name='update_user'),
        path('waiver/<int:student_id>/', WaiverView.as_view(), name='waiver'),
        path('waiver_recreate/<int:student_id>/', WaiverRecreateView.as_view(), name='waiver_recreate')
]

wpa_project/wpa_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from student_app.views import SignupView

urlpatterns = [
    path('', include('student_app.urls', namespace='registration')),
    path('accounts/signup/', SignupView.as_view(), name="account_signup"),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('contact_us/', include('contact_us.urls', namespace='contact_us')),
    path('events/', include('event.urls', namespace='events')),
    path('facebook/', include('facebook.urls', namespace='facebook')),
    path('information/', include('info.urls', namespace='information')),
    path('inventory/', include('inventory.urls', namespace='inventory')),
    path('joad/', include('joad.urls', namespace='joad')),
    path('membership/', include('membership.urls', namespace='membership')),
    path('minutes/', include('minutes.urls', namespace='minutes')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('programs/', include('program_app.urls', namespace='programs')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wpa_project/student_app/models/student.py
import logging
from django.db import models
from django.conf import settings
from django.apps import apps

from .student_family import StudentFamily

from django.utils import timezone
logger = logging.getLogger(__name__)


class Student(models.Model):
    student_family = models.ForeignKey(StudentFamily, on_delete=models.SET_NULL, null=True, default=None)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, default=None)

    # user fields
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    dob = models.DateField()
    email = models.EmailField(null=True, default=None, unique=True)

    # hidden fields
    safety_class = models.DateField(null=True)
    covid_vax = models.BooleanField(default=False)
    signature = models.ImageField(upload_to="signatures/%Y/%m/%d/", null=True)
    signature_pdf = models.FileField(upload_to="signatures/%Y/%m/%d/", null=True)
    is_joad = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_user(self):
        User = apps.get_model('student_app', 'User')
        if self.user is None:
            return User.objects.filter(student__student_family=self.student_family)
        else:
            users = User.objects.filter(id=self.user.id)
        return users

wpa_project/joad/forms/student_search_form.py
from django.forms import TextInput, CheckboxInput
from django import forms

from student_app.forms import SearchColumnsForm


class SearchColumnsForm(SearchColumnsForm):
    last_event = forms.BooleanField(required=False, label='Show pin records from last event')

wpa_project/contact_us/views/message_view.py
import logging
from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.conf import settings
from ipware import get_client_ip

from ..forms import MessageForm
from ..models import Category, Message
from ..tasks import send_contact_email
from student_app.models import Student
from allauth.account.models import EmailAddress
from src.mixin import BoardMixin
logger = logging.getLogger(__name__)


class MessageListView(BoardMixin, ListView):
    model = Message
    paginate_by = 20  # if pagination is desired
    template_name = 'contact_us/message_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['spam_list'] = self.kwargs.get('spam', False)
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.kwargs.get('spam', False):
            queryset = queryset.filter(spam_category='spam')
        else:
            queryset = queryset.exclude(spam_category='spam')
        return queryset.order_by('-created_time')


class MessageView(FormView):
    template_name = 'contact_us/message.html'
    form_class = MessageForm
    success_url = reverse_lazy('registration:index')
    message = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # self.request.session.pop('recaptcha_score')
        if self.request.user.is_authenticated:
            context['probably_human'] = True
        else:
            score = self.request.session.get('recaptcha_score', 0)
            logging.warning(score)
            context['probably_human'] = score > 0.5
        # cat = Category.objects.filter(title='Website').last()
        # if cat is not None:
        #     context['email'] = cat.email
        # else:
        #     context['email'] = settings.DEFAULT_FROM_EMAIL
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        message = self.kwargs.get("message_id", None)
        if self.request.user.is_authenticated and self.request.user.has_perm('student_app.board') and message is not None:
            self.message = get_object_or_404(Message, pk=message)
            kwargs['instance'] = self.message
        kwargs['user'] = self.request.user
        return kwargs

    def get_initial(self):
        self.initial = super().get_initial()
        if 'message_id' not in self.kwargs and self.request.user.is_authenticated:
            student = Student.objects.filter(user=self.request.user).last()
            if student is not None:
                self.initial['contact_name'] = f'{student.first_name} {student.last_name}'
                self.initial['email'] = EmailAddress.objects.get_primary(self.request.user)
        return self.initial

    def form_invalid(self, form):
        logging.warning(form.errors)
        return super().form_invalid(form)

    def form_valid(self, form):
        def make_error():
            form.add_error(None, 'In order to prevent spam we are unable to process request at this time.')
            form.can_submit = False
            self.request.session['contact_us'] = timezone.now().isoformat()
            return self.form_invalid(form)

        if self.request.user.is_authenticated and self.request.user.is_board:
            pass
        else:
            # check users history
            recent_time = timezone.now() - timezone.timedelta(hours=2)
            if 'contact_us' in self.request.session:
                if timezone.datetime.fromisoformat(self.request.session['contact_us']) > recent_time:
                    return make_error()
            recent = Message.objects.filter(created_time__gt=recent_time, email=form.cleaned_data['email'])
            if recent:
                return make_error()

        # save record
        self.request.session['contact_us'] = timezone.now().isoformat()
        message = form.save()
        client_ip, is_routable = get_client_ip(self.request)
        send_contact_email.delay(message.id, client_ip)
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        return super().post(request, *args, **kwargs)

wpa_project/joad/views/student_list_view.py
from student_app.views import StudentList
from ..forms import SearchColumnsForm

import logging
logger = logging.getLogger(__name__)


class StudentListView(StudentList):
    template_name = 'joad/student_list.html'
    form_class = SearchColumnsForm
    paginate_by = 20
    last_event = False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['last_event'] = self.last_event
        return context

    def get_queryset(self):
        queryset = super().get_queryset().filter(is_joad=True).exclude(user__groups__name='staff').order_by('last_name')
        if self.form.is_valid():
            self.last_event = self.form.cleaned_data['last_event']
        return queryset

wpa_project/student_app/templates/student_app/acc_active_email.html
{% autoescape off %}  
Hi {{ user.username }},  
Please click on the link to confirm your registration,http://{{ domain }}{% url 'registration:activate' uidb64=uid token=token %}
If you think, it's not you, then just ignore this email.  
{% endautoescape %}

wpa_project/student_app/templates/student_app/covid_policy.html
{% extends 'base.html' %}

{% block title %} Covid-19 Policy {% endblock %}

{% block main %}
  <div class="row justify-content-center">
    <div class="col-4 text-center"><h2> Covid-19 Policy </h2></div>
  </div>

    <p>
        {% include "program_app/covid_policy.txt" %}
    </p>

    <button class="btn btn-primary" onclick="goBack()">Go Back</button>

    <script>
        function goBack() {
          window.history.back();
        }
    </script>
{% endblock %}

wpa_project/student_app/templates/student_app/message.html
{% extends 'base.html' %}

{% block title %}
    Message
{% endblock %}

{% block main %}
    <h3>{{message}}</h3>
{% endblock %}

wpa_project/student_app/templates/student_app/profile.html
{% extends 'base.html' %}

{% block title %} Profile {% endblock %}
{% block script %}
    {% load static %}
    <script src="{% static 'js/profile.js' %}"></script>
    {% if student_family %}
        <script src="{% static 'js/class_cancel.js' %}"></script>
    {% endif %}
    <script nonce="{{request.csp_nonce}}">
        let student_table_url = "{% url 'registration:student_table' %}"
        let add_student_url = "{% url 'registration:add_student' %}"
        let url_student_family_api = "{% url 'registration:student_family' %}"
        let url_instructor_update = "{% url 'registration:instructor_update' %}"
        let url_class_registered_table = "{% url 'events:cancel' %}"
        {% if student_family %} let family = true {% else %} let family = false {% endif %}
    </script>
{% endblock %}

{% block left %}

{% endblock %}

{% block main %}
    <div id="div-can-register-top" class="d-flex flex-row-reverse pt-3 can-register-top">
        <h4><a href="{% url 'programs:calendar' %}" class="can-register-top">
            Register for an Introductory Archery class.
        </a></h4>
    </div>
    <div class="row p-3 align-items-center mx-auto">
        <div class="col-12">
            {% if this_student %}
                <h2> {{ this_student.first_name }} {{ this_student.last_name }}'s Profile Page</h2>
            {% else %}
                <h2> Profile Page </h2>
            {% endif %}
        </div>
    </div>
    <div class="row px-3" id="div-instruct"></div>
    {% if this_student is None %}
        <div class="row px-2" id="this-student-div"></div>
    {% endif %}
    {% if not student_family.id %}
        {% include 'student_app/student_family_insert.html' %}
    {% endif %}
    <div class="row px-3 pt-3 align-items-center mx-auto">
        <div class="col-12">
            <h3> Students </h3>
            <input type="hidden" id="this-student" value="{{ this_student }}">
        </div>
    </div>
    <div class="row">
        <div class="col-1"></div>
        <div class="col px-3 container" id="student-table-div"></div>
        <div class="col-1"></div>
    </div>

    <div class="row px-2 container" id="student_add_div"></div>
    <div class="flex-row px-3 mx-5">
        <button id="btn-add-student" class="btn btn-primary" type="button" name="button">
            Add Student
        </button>
    </div>

    <div id="can-register" class="row pt-3">
        Now that you have added a student you can&nbsp;
        <a href="{% url 'programs:class_registration' %}">register</a>
        &nbsp;for a class. You can also click on Classes in the nav bar.
    </div>

    {% if student_family %}
        <div class="row px-3 pt-3 align-items-center mx-auto">
            <div class="col">
            <h3> Classes </h3>
            </div>
        </div>
        <div class="row px-3 pt-3 align-items-center mx-auto" id="registered_classes">
            <div class="col-1"></div>
            <div class="col">
                <div class="row">{% include "program_app/register.txt" %}</div>
                <div class="row pt-1" id="registered_table"></div>
                <div class="row pt-1 align-items-center mx-auto">
                    Past class attendance:
                    {% include 'program_app/tables/history_table.html' %}
                </div>
            </div>
            <div class="col-1"></div>
        </div>

    {% endif %}

    <div class="row px-3 pt-3 align-items-center mx-auto">
        <div class="col">
        <h3> Payment </h3>
        <p class="px-4"><a href="{% url 'payment:card_manage' %}">Manage Credit Cards</a></p>
        </div>
    </div>

    <div class="flex-row p-3 mx-3" id="theme-div">
        <form method="post" action="{% url 'registration:theme' %}">{% csrf_token %}
            {{ theme_form.as_p }}
            <button id="theme-submit"  type="submit" class="btn btn-primary">Update Theme</button>
        </form>
    </div>

    {% if user.is_instructor %}
        <div class="row p-3 align-items-center mx-auto">
            <div class="col-12">
                <h3> Instructor </h3>
            </div>
        </div>
        <div class="row p-3 mx-auto" id="instructor-info-div">
            <div class="col-1"></div>
            <div class="col">
                <table class="table table-bordered">
                    <tbody>
                        <tr>
                            <td>USAA Archery Instructor Certificate Expiration Date:</td>
                            <td>Level</td>
                            <td rowspan="2">
                                <button id="btn-instructor" class="btn btn-primary m-2" type="button" name="button">
                                    Edit
                                </button>
                            </td>
                        </tr>
                        <tr>
                            <td id="instructor_exp_date">{{ user.instructor_expire_date }}</td>
                            <td id="instructor_level">{{ user.instructor_level }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="col-1"></div>
        </div>
        <div class="row p-3 mx-auto" id="instructor-form-div">
        </div>
    {% endif %}
    {% if student_family.id %}
    {% include 'student_app/student_family_insert.html' %}
        <div class="row px-3">
            <div>
                <a class="btn btn-danger" href="{% url 'registration:delete_student_family' student_family.id%}">
                    Delete Account
                </a>
            </div>
        </div>
    {% endif %}
{% endblock %}

wpa_project/student_app/templates/student_app/search_result.html
{% extends 'base.html' %}

{% block title %}
    Student Search
{% endblock %}

{% block script %}
    {% load static %}
    <script src="{% static 'js/search.js' %}"></script>
    <script src="{% static 'js/class_cancel.js' %}"></script>
    <script nonce="{{request.csp_nonce}}">
        let student_table_url = "{% url 'registration:student_table' %}"
        let add_student_url = "{% url 'registration:add_student' %}"
        let url_student_family_api = "{% url 'registration:student_family' %}"
        let url_class_registered_table = "{% url 'events:cancel' student_family.id %}"
    </script>
{% endblock %}

{% block main %}
    <div class="row" message_text="{{ message }}" hidden id="message"><h3>"{{ message }}"</h3></div>
    <div class="p-2">
        <table class="table table-bordered">
            <thead>
                <th> </th>
                <th> First Name </th>
                <th> Last Name </th>
                <th> Date of Birth </th>
                <th> Safety Class Date </th>
                <th> Waiver </th>
                <th> Membership Expire Date </th>
            </thead>
            <tbody>
                {% for student in student_family.student_set.all %}
                    <tr>
                        <td>
                            <button id="btn-edit-{{ student.id }}" class="btn btn-primary" type="button"
                                    student-id="{{ student.id }}">
                                Edit
                            </button>
                        </td>
                        <td>{{ student.first_name }}</td>
                        <td>{{ student.last_name }}</td>
                        <td>{{ student.dob }}</td>
                        <td>{{ student.safety_class }}</td>
                        <td>
                            {% if student.signature_pdf %}
                                <a target="_blank" href="{% url 'registration:pdf' student.id %}">Waiver</a>
                            {% endif %}
                        </td>
                        <td>
                            {% for member in student.member_set.all %}
                                <a href="{% url 'membership:membership' student_family.id %}">
                                    {{ member.expire_date }}
                                </a>
                            {% endfor %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="container" id="student_add_div"></div>
    <div id="student-family-form" class="row px-3"></div>

    <div id="student-family-address" class="row px-3">
        <div class="col-1"></div>
        <div class="col px-3">
            <div id="address1" class="row">{{ student_family.street }} </div>
            <div id="address2" class="row">
                {{ student_family.city }} {{ student_family.state }} {{ student_family.post_code }}
            </div>
            <div id="phone" class="row">{{ student_family.phone }}</div>
            <div class="flex-row m-2">
                <button id="btn-address-edit" class="btn btn-primary" type="button" name="button"
                        family_id="{{ student_family.id }}">
                    Edit Address
                </button>
            </div>
        </div>
    </div>
    {% if perms.student_app.board and student_family.id %}
        <div class="row p-4">
                Past class attendance:
                {% include 'program_app/tables/history_table.html' %}
        </div>
        <div class="row p-4">
                Upcoming registrations:
        </div>
        <div class="row pt-1" id="registered_table"></div>
        <div class="row p-4">
            <div class="col">Registration date: {{ student_family.registration_date}} </div>
            <a class="col m-2 btn btn-primary" href="{% url 'programs:class_registration_admin' student_family.id %}" role="button">
                Admin Registration
            </a>
        </div>
        <div class="row pt-4">
            <h4>Volunteer Points:</h4>
            <div class="d-flex flex-row">
                <div>Points: {{ volunteer_points }}</div>
                <a class="m-2 btn btn-primary" href="{% url 'events:volunteer_record'%}?student_family={{ student_family.id }}" role="button">
                    Modify Points
                </a>
            </div>
        </div>
        <div class="row pt-4">
            <a href="{% url 'membership:membership' student_family.id %}"> Membership </a>
        </div>
    {% endif %}

{% endblock %}

wpa_project/student_app/templates/student_app/student_search.html
{% extends 'base.html' %}

{% block title %}
    Student Search
{% endblock %}

{% block main %}
    <div class="row" message_text="{{ message }}" hidden id="message"><h3>"{{ message }}"</h3></div>
    <div class="row p-3">
        <form method="post" autocomplete="off" class="form" action="{% url 'registration:search' %}">
        {% csrf_token %} {{ email_form.non_field_errors }}
            <div class="row m-1">
                <h4>
                    Search by Email
                </h4>
            </div>
            <div class="row">
                <div class="col input-group input-group-md">
                    {{ email_form.email }}{{ email_form.email.errors }}
                </div>
                <div class="col">
                    <button class="btn btn-primary" type="submit">Search</button>
                </div>
            </div>
        </form>
    </div>

    <div class="row p-3">
        <form method="post" autocomplete="off" class="form" action="{% url 'registration:search_name' %}">
        {% csrf_token %} {{ name_form.non_field_errors }}
            <div class="row m-1">
                <h4>
                    Search by Name
                </h4>
            </div>
            <div class="row">
                <div class="col">
                    <div class="row">
                        <div class="col input-group input-group-md">
                                {{ name_form.first_name }}
                        </div>
                        <div class="col input-group input-group-md">
                                {{ name_form.last_name }}
                        </div>
                    </div>
                </div>
                <div class="col">
                    <button class="btn btn-primary" type="submit">Search</button>
                </div>
            </div>
        </form>
    </div>

    <div class="row p-3">
        <form method="post" autocomplete="off" class="form" action="{% url 'registration:search_phone' %}">
        {% csrf_token %} {{ phone_form.non_field_errors }} {{ phone_form.name_of_field.errors }}
            <div class="row m-1">
                <h4>
                    Search by Phone
                </h4>
            </div>
            <div class="row">
                <div class="col input-group input-group-md">
                        {{ phone_form.phone }}{{ phone_form.phone.errors }}
                </div>
                <div class="col">
                    <button class="btn btn-primary" type="submit">Search</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}