wpa_project/info/urls.py
from django.urls import path
from .views import *
app_name = 'info'

urlpatterns = [
    path('announcement_form/', AnnouncementFormView.as_view(), name='announcement_form'),
    path('announcement_form/<int:pk>', AnnouncementFormView.as_view(), name='announcement_form'),
    path('announcement_list/', AnnouncementList.as_view(), name='announcement_list'),
    path('category/', CategoryView.as_view(), name='category'),
    path('category/<int:category_id>/', CategoryView.as_view(), name='category'),
    path('category_delete/<int:category_id>/', CategoryDeleteView.as_view(), name='category_delete'),
    path('category_list/', CategoryListView.as_view(), name='category_list'),
    path('faq', FaqList.as_view(), name='faq'),
    path('info/<str:info>/', InfoView.as_view(), name='info'),
    path('edit/', FaqFormView.as_view(), name='edit'),
    path('edit/<int:faq_id>/', FaqFormView.as_view(), name='edit'),
    path('policy/', PolicyFormView.as_view(), name='policy'),
    path('policy/<int:policy>/', PolicyFormView.as_view(), name='policy'),
    path('policy/<int:policy>/<int:version>/', PolicyFormView.as_view(), name='policy'),
    path('policy_list', PolicyListView.as_view(), name='policy_list'),
    path('staff_list/', StaffList.as_view(), name='staff_list'),
    path('staff_profile_form/', StaffProfileFormView.as_view(), name='staff_profile_form'),
    path('staff_profile_form/<int:pk>/', StaffProfileFormView.as_view(), name='staff_profile_form'),
]

wpa_project/wpa_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from student_app.views import SignupView

urlpatterns = [
    path('', include('student_app.urls', namespace='registration')),
    path('accounts/signup/', SignupView.as_view(), name="account_signup"),
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('contact_us/', include('contact_us.urls', namespace='contact_us')),
    path('events/', include('event.urls', namespace='events')),
    path('facebook/', include('facebook.urls', namespace='facebook')),
    path('information/', include('info.urls', namespace='information')),
    path('inventory/', include('inventory.urls', namespace='inventory')),
    path('joad/', include('joad.urls', namespace='joad')),
    path('membership/', include('membership.urls', namespace='membership')),
    path('minutes/', include('minutes.urls', namespace='minutes')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('programs/', include('program_app.urls', namespace='programs')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wpa_project/info/models/annoucement_model.py
from django.db import models
from django.template import Context, Template
from django.utils import timezone
import logging
logger = logging.getLogger(__name__)

STATUS = (
    (0, "Draft"),
    (1, "Publish"),
    (2, 'Obsolete')
)


class Announcement(models.Model):
    begin_date = models.DateTimeField(default=timezone.now)
    end_date = models.DateTimeField(default=timezone.now)
    announcement = models.TextField()
    status = models.IntegerField(choices=STATUS, default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):  # pragma: no cover
        return self.announcement

    def rendered_announcement(self):
        return Template(self.announcement).render(Context({}))

wpa_project/info/models/category_model.py
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.title}'

wpa_project/info/models/staff_profile_model.py
from django.db import models

from student_app.models import Student
import logging
logger = logging.getLogger(__name__)

STATUS = (
    (0, "Draft"),
    (1, "Publish"),
    (2, 'Obsolete')
)


class StaffProfile(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="profiles/%Y/%m/")
    bio = models.TextField()
    status = models.IntegerField(choices=STATUS, default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-student__user__is_board']

    def __str__(self):  # pragma: no cover
        return self.student

wpa_project/info/forms/announcement_form.py
from src.model_form import MyModelForm
from ..models import Announcement


class AnnouncementForm(MyModelForm):

    class Meta(MyModelForm.Meta):
        model = Announcement
        required_fields = ['begin_date', 'end_date', 'announcement', 'status']
        optional_fields = []
        fields = optional_fields + required_fields

wpa_project/info/forms/category_form.py
from src.model_form import MyModelForm
from ..models import Category


class CategoryForm(MyModelForm):

    class Meta(MyModelForm.Meta):
        model = Category
        required_fields = ['title']
        optional_fields = []
        fields = optional_fields + required_fields

wpa_project/info/forms/faq_form.py
from django.forms import Form, ModelChoiceField, RadioSelect, CharField
from src.model_form import MyModelForm
from ..models import Category, Faq


class FaqForm(MyModelForm):

    class Meta(MyModelForm.Meta):
        model = Faq
        required_fields = ['category', 'question', 'answer', 'status']
        optional_fields = []
        fields = optional_fields + required_fields


class FaqFilterForm(Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'] = ModelChoiceField(Category.objects.all(), empty_label="---------", required=False)


class FaqSearchForm(Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['search'] = CharField(required=False)

wpa_project/info/views/annoucement_view.py
from django.views.generic import ListView
from django.views.generic.edit import FormView
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils import timezone
from ..models import Announcement
from ..forms import AnnouncementForm
from src.mixin import BoardMixin
import logging
logger = logging.getLogger(__name__)


class AnnouncementFormView(BoardMixin, FormView):
    model = Announcement
    form_class = AnnouncementForm
    template_name = 'info/preview_form.html'
    success_url = reverse_lazy('info:announcement_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Announcement Form'
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if self.kwargs.get('pk', None) is not None:
            kwargs['instance'] = get_object_or_404(Announcement, pk=self.kwargs['pk'])
        return kwargs

    def form_valid(self, form):
        logger.warning(form.cleaned_data)
        form.save()
        return super().form_valid(form)


class AnnouncementList(ListView):
    """
    Return all announcements that are with status 1 (published) and order from the oldest one.
    """
    model = Announcement
    template_name = 'info/announcement_list.html'
    paginate_by = 10

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['announcements'] = context.pop('object_list')
        return context

    def get_queryset(self):
        object_list = self.model.objects.filter(
            end_date__gte=timezone.now(),
            begin_date__lte=timezone.now(),
            status=1,
        )
        if self.request.user.is_authenticated and self.request.user.has_perm('student_app.board'):
            object_list = self.model.objects.filter(
                end_date__gte=timezone.now() - timezone.timedelta(days=30),
                begin_date__lte=timezone.now(),
            )
        return object_list.order_by('-created_at')

wpa_project/info/views/category_view.py
import logging
from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from django.views.generic.base import View
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from ..forms import CategoryForm
from ..models import Category
from src.mixin import BoardMixin

logger = logging.getLogger(__name__)


class CategoryDeleteView(BoardMixin, View):
    def post(self, request, category_id):
        category = get_object_or_404(Category, pk=category_id)
        category.delete()
        return HttpResponseRedirect(reverse_lazy('info:category_list'))


class CategoryListView(BoardMixin, ListView):
    model = Category
    paginate_by = 100  # if pagination is desired
    queryset = Category.objects.all().order_by('title')


class CategoryView(BoardMixin, FormView):
    template_name = 'contact_us/category.html'
    form_class = CategoryForm
    success_url = reverse_lazy('info:category_list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if 'category_id' in self.kwargs:
            kwargs['instance'] = get_object_or_404(Category, pk=self.kwargs['category_id'])
        return kwargs

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

wpa_project/info/views/faq_view.py
from django.views.generic import ListView
from django.views.generic.edit import FormView
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy

from ..models import Faq
from ..forms import FaqForm, FaqFilterForm, FaqSearchForm
from src.mixin import BoardMixin

import logging
logger = logging.getLogger(__name__)


class FaqFormView(BoardMixin, FormView):
    model = Faq
    form_class = FaqForm
    template_name = 'student_app/form_as_p.html'
    faq = None
    success_url = reverse_lazy('info:faq')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'FAQ Form'
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if self.faq:
            kwargs['instance'] = self.faq
        return kwargs

    def form_valid(self, form):
        logger.warning(form.cleaned_data)
        form.save()
        return super().form_valid(form)

    def test_func(self):
        if self.kwargs.get('faq_id', None) is not None:
            self.faq = get_object_or_404(Faq, pk=self.kwargs['faq_id'])
        return super().test_func()


class FaqList(ListView):
    """
    Return all posts that are with status 1 (published) and order from the latest one.
    """
    model = Faq
    template_name = 'info/faq_list.html'
    paginate_by = 10

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['form'] = FaqFilterForm(initial=self.request.GET)
        context['search_form'] = FaqSearchForm(initial=self.request.GET)
        return context

    def get_queryset(self):
        form = FaqFilterForm(self.request.GET)
        object_list = self.model.objects.filter(status=1)
        if form.is_valid():
            if form.cleaned_data['category'] is not None:
                object_list = object_list.filter(category=form.cleaned_data['category'])
        else:
            logger.warning(form.errors)
        search_form = FaqSearchForm(self.request.GET)
        if search_form.is_valid():
            object_list = object_list.filter(Q(question__icontains=search_form.cleaned_data['search']) |
                                             Q(answer__icontains=search_form.cleaned_data['search']))
        return object_list.order_by('-created_at')

wpa_project/info/views/info_view.py
from django.views.generic import ListView
from ..models import Article

import logging
logger = logging.getLogger(__name__)


class InfoView(ListView):
    model = Article
    template_name = 'info/info.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['title'] = self.kwargs.get('info', '').replace('_', ' ')
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(page__page=self.kwargs.get('info', 'about'), status=1)
        return queryset.order_by('position')

wpa_project/info/views/policy_view.py
from django.views.generic import FormView, ListView
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.forms.models import model_to_dict

from ..models import Policy
from ..forms import PolicyTextForm
from src.mixin import BoardMixin
import logging
logger = logging.getLogger(__name__)


class PolicyFormView(FormView):
    model = Policy
    form_class = PolicyTextForm
    template_name = 'info/policy.html'
    success_url = reverse_lazy('info:announcement_list')
    policy = None
    version = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.policy:
            context['title'] = self.policy.title
            if self.version is None:
                context['current'] = self.policy.policytext_set.filter(status=1).first()
                context['history'] = self.policy.policytext_set.all()
        else:
            context['title'] = 'Policy Form'
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if 'policy' in self.kwargs:
            self.policy = get_object_or_404(Policy, pk=self.kwargs.get('policy'))
            if self.kwargs.get('version', None) is not None:
                self.version = self.policy.policytext_set.get(pk=self.kwargs['version'])

        if self.policy is not None:
            if self.version is None:
                kwargs['initial'] = model_to_dict(self.policy.policytext_set.first())
                kwargs['initial']['status'] = 0
            else:
                # kwargs['initial'] = model_to_dict(self.version)
                kwargs['instance'] = self.version
            kwargs['initial']['title_text'] = self.policy.title
            kwargs['initial']['title_access'] = self.policy.access
        kwargs['initial']['user'] = self.request.user
        return kwargs

    def form_invalid(self, form):
        logger.warning(form.errors)
        return super().form_invalid(form)

    def form_valid(self, form):
        if not self.request.user.has_perm('student_app.board'): # pragma: no cover
            return self.form_invalid(form)

        if self.policy is None:
            self.policy = Policy.objects.create(title=form.cleaned_data.get('title_text'))
        else:
            self.policy.title = form.cleaned_data.get('title_text')
            self.policy.access = form.cleaned_data.get('title_access')
            self.policy.save()
        pt = form.save(commit=False)
        pt.title = self.policy
        pt.is_html = True
        pt.save()

        self.success_url = reverse_lazy('info:policy', kwargs={'policy': self.policy.id})

        return super().form_valid(form)


class PolicyListView(BoardMixin, ListView):
    model = Policy

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset

wpa_project/info/views/staff_profile_view.py
from django.views.generic import ListView
from django.views.generic.edit import FormView
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils import timezone
from django.db.models import Q

from ..models import StaffProfile
from ..forms import StaffProfileForm
from student_app.models import Student

import logging
logger = logging.getLogger(__name__)


class StaffProfileFormView(UserPassesTestMixin, FormView):
    model = StaffProfile
    form_class = StaffProfileForm
    template_name = 'info/preview_form.html'
    success_url = reverse_lazy('info:staff_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Staff Profile Form'
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if self.kwargs.get('pk', None) is not None:
            kwargs['instance'] = get_object_or_404(StaffProfile, pk=self.kwargs['pk'])
        return kwargs

    def form_invalid(self, form):
        logger.warning(form.errors)
        return super().form_invalid(form)

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def test_func(self):
        if self.request.user.is_authenticated:
            return self.request.user.is_superuser
        return False


class StaffList(ListView):
    model = Student
    template_name = 'info/staff_list.html'

    def get_queryset(self):
        d = timezone.now() - timezone.timedelta(days=60)
        object_list = self.model.objects.filter(
            (Q(user__groups__name='staff') &
            Q(registration__event__event_date__gte=d) &
            Q(registration__attended=True)) | Q(user__groups__name='board')
        )

        return object_list.distinct().order_by('-user__is_board', '-user__is_instructor')

wpa_project/info/templates/info/announcement_form.html
{% extends 'base.html' %}

{% block title %} Announcement Form {% endblock %}

{% load static %}
{% block script %}
    <script src="{% static 'js/announcement.js' %}"></script>
{% endblock %}

{% block main %}
    <div class="row" message_text="{{ message }}" hidden id="message"><h3>"{{ message }}"</h3></div>

    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary m-2" type="button" id="btn-announcement-preview">Preview</button>
        <button class="btn btn-primary m-2" type="submit" name="button">Submit</button>
    </form>
    Preview:
    <div class="row border">

        <div class="container" id="announcement-container"></div>
    </div>
{% endblock %}

wpa_project/info/templates/info/announcement_insert.html
{% if announcements %}
    <h3>Announcements:</h3>
{% endif %}
{% for announcement in announcements %}
    <div class="row ps-2">
        <div class="container">
            {{ announcement.announcement|safe }}
        </div>
    </div>
    {% if perms.student_app.board %}
        <div class="row ps-4">
            <div class="d-flex flex-column">
                <div><a href="{% url 'info:announcement_form' announcement.id %}">{{ announcement.id }}</a></div>
                <div>Starts: {{ announcement.begin_date }}</div>
                <div>Ends: {{ announcement.end_date }}</div>
                <div>Status: {{announcement.status }}</div>
            </div>
        </div>
    {% endif %}
    <hr>
{% endfor %}

wpa_project/info/templates/info/announcement_list.html
{% extends 'base.html' %}

{% block title %} Announcements {% endblock %}


{% load static %}
{% block left %}
    {% if perms.student_app.board %}
        <a href="{% url 'info:announcement_form' %}" role="button" class="btn btn-primary btn-sm m-1"> Add Announcement</a>
    {% endif %}
{% endblock %}

{% block main %}
    <div class="container">
        {% include 'info/announcement_insert.html' %}
    </div>

    {% include 'student_app/paginate.html' %}
{% endblock %}

wpa_project/info/templates/info/category_list.html
{% extends 'base.html' %}

{% block title %} FAQ Category List {% endblock %}


{% block main %}
    <div class="m-2"><h5>FAQ Categories:</h5></div>
    {% for category in object_list %}
        <div class="d-flex flex-row m-2">
            <div class="col">
                <a href="{% url 'information:category' category.id %}">
                    {{ category.title }}
                </a>
            </div>

        </div>
    {% empty %}
        <h6>No categories yet.</h6>
    {% endfor %}

    <div class="d-flex flex-row m-2">
        <div class="m-3">
            <a href="{% url 'information:category'%}" class="btn btn-primary" role="button">
                Add Category
            </a>
        </div>
    </div>

{% endblock %}

wpa_project/info/templates/info/faq_list.html
{% extends 'base.html' %}

{% block title %} Faq {% endblock %}

{% load static %}
{% block left %}
    {% if perms.student_app.board %}
        <a href="{% url 'info:edit' %}" role="button" class="btn btn-primary m-1"> Add FAQ</a>
    {% endif %}
{% endblock %}

{% block main %}
    <div class="row justify-content-center">
        <div class="text-center">
            <h2> Frequently Asked Questions </h2>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form class="form m-2" method="get">
                <div class="m-2"><h5>Filter by category:</h5></div>

                <div class="d-flex flex-row m-2">
                    <div class="m-2 fieldWrapper">
                        {{ form.category }}
                    </div>
                </div>
                <div class="d-flex flex-row m-2">
                    <input class="btn btn-primary" type="submit" value="Submit">
                </div>
            </form>
        </div>
        <div class="col border-start">
            <form class="form m-2" method="get">
                <div class="m-2"><h5>Search:</h5></div>

                <div class="d-flex flex-row m-2">
                    <div class="m-2 fieldWrapper">
                        {{ search_form.search }}
                    </div>
                </div>
                <div class="d-flex flex-row m-2">
                    <input class="btn btn-primary" type="submit" value="Submit">
                </div>
            </form>
        </div>
    </div>
    <hr>
    {% for faq in object_list %}
        <div class="row">
            {% if perms.student_app.board %}
                <a href="{% url 'info:edit' faq.id %}"><h4>{{ faq.question }}</h4></a>
            {% else %}
                <h4>{{ faq.question }}</h4>
            {% endif %}
            <p>
                Categories:
                {% for category in faq.category.all %}{{ category }}{% if not forloop.last %},&nbsp{% endif %}{% endfor %}
            </p>
            <div class="mx-3">
                <p> {{ faq.rendered_answer|safe }}</p>
            </div>
        </div>
        <hr>
    {% endfor %}

    {% include 'student_app/paginate.html' %}
{% endblock %}

wpa_project/info/templates/info/info.html
{% extends 'base.html' %}

{% block title %} {{ title|title }} {% endblock %}

{% load static %}
{% block main %}
    {% for object in object_list %}
        <div class="container"> {{object.article|safe}} </div>
    {% endfor %}

{% endblock %}

{% block right %}
    <div id="login-div"></div>
{% endblock %}

wpa_project/info/templates/info/policy.html
{% extends 'base.html' %}

{% load static %}
{% block script %}
    <script src="{% static 'js/info_preview.js' %}"></script>
    {{ form.media }}
{% endblock %}
{% block title %} {{title}} {% endblock %}

{% block main %}
    <div class="row" message_text="{{ message }}" hidden id="message"><h3>"{{ message }}"</h3></div>
    {% if current %}
        <h1 class="text-center"> {{current.title.title}} </h1>
        <div>
            {% if current.is_html %}
                {{ current.policy|safe }}
            {% else %}
                {{ current.policy|linebreaks }}
            {% endif %}
        </div>
    {% endif %}
    {% if perms.student_app.board %}
        <hr>
        <h4 class="text-center"> Board only below this line </h4>
        <form method="post">{% csrf_token %}
            <p> {{ form.title_text.label }} {{ form.title_text }} {{ form.title_text.errors }}</p>
            <p> {{ form.title_access.label }} {{ form.title_access }} {{ form.title_access.errors }}</p>
            <p> {{ form.status.label }} {{ form.status }} {{ form.status.errors }}</p>
            <p> {{ form.policy.label }} {{ form.policy }} {{ form.policy.errors }}</p>
            <p> {{ form.is_html.label }} {{ form.is_html }} {{ form.is_html.errors }}</p>
            <button class="btn btn-primary m-2" type="button" id="btn-info-preview">Preview</button>
            <button class="btn btn-primary m-2" type="submit" name="button">Submit</button>
        </form>
        <div class="row border">
            <div class="container" id="info-preview-container"></div>
        </div>
        {% if history %}
            <hr>
            <h3 class="text-center"> History </h3>
            {% for policy in history %}
                <div class="row border">
                    <div class="row px-3">
                        {% if policy.is_html %}
                            {{ policy.policy|safe }}
                        {% else %}
                            {{ policy.policy|linebreaks }}
                        {% endif %}
                    </div>
                    <div class="d-flex flex-row justify-content-around">
                        <div>
                            Status: {{ policy.get_status_display}}
                            {% if current and policy.id == current.id %} Current {% endif %}
                        </div>
                        <div>Created Time: {{ policy.created_at }}</div>
                        <div>Created By: {{ policy.user.student_set.last }}</div>
                        <div>
                            <a class="btn btn-primary" href="{% url 'information:policy' policy.title.id policy.id %}" role="button">
                                edit
                            </a>
                        </div>
                    </div>
                </div>

            {% endfor %}
        {% endif %}
    {% endif %}
{% endblock %}

wpa_project/info/templates/info/policy_list.html
{% extends 'base.html' %}

{% block title %} Policy List {% endblock %}


{% block main %}
    <div class="m-2"><h5>FAQ Categories:</h5></div>
    {% for policy in object_list %}
        <div class="d-flex flex-row m-2">
            <div class="col">
                <a href="{% url 'information:policy' policy.id %}">
                    {{ policy.title }}
                </a>
            </div>

        </div>
    {% empty %}
        <h6>No categories yet.</h6>
    {% endfor %}

    <div class="d-flex flex-row m-2">
        <div class="m-3">
            <a href="{% url 'information:policy'%}" class="btn btn-primary" role="button">
                Add Policy
            </a>
        </div>
    </div>

{% endblock %}

wpa_project/info/templates/info/preview_form.html
{% extends 'base.html' %}

{% block title %} {{ title }}{% endblock %}

{% load static %}
{% block script %}
    <script src="{% static 'js/info_preview.js' %}"></script>
{% endblock %}

{% block main %}
    <div class="row" message_text="{{ message }}" hidden id="message"><h3>"{{ message }}"</h3></div>

    <form method="post" {% if form.multipart %} enctype="multipart/form-data" {% endif %}>
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-primary m-2" type="button" id="btn-info-preview">Preview</button>
        <button class="btn btn-primary m-2" type="submit" name="button">Submit</button>
    </form>
    Preview:
    <div class="row border">

        <div class="container" id="info-preview-container"></div>
    </div>
{% endblock %}

wpa_project/info/templates/info/staff_list.html
{% extends 'base.html' %}

{% block title %} Staff List {% endblock %}


{% load static %}

{% block main %}
    <div class="row justify-content-center">
        <div class="text-center">
            <h2> Active Volunteer Staff List </h2>
        </div>
    </div>
    
    {% for staff in object_list %}
        <div class="row border m-2" style="background-color: whitesmoke; color: white;">
            <div class="flex-row justify-content-between" style="padding: 16px; background-color: black;">
                <h4>{{ staff.first_name }}</h4>
                <span sytle="float: left;">
                    {% if staff.user.is_board and staff.user.is_instructor%}
                        Board Member and Instructor
                    {% elif staff.user.is_board %}
                        Board Member
                    {% elif staff.user.is_instructor %}
                        Instructor
                    {% else %}
                        Staff
                    {% endif %}
                </span>
                <br>
                <div>
                    {% if user.is_superuser %}
                        {% if staff.staffprofile_set.last %}
                            <a href="{% url 'info:staff_profile_form' staff.staffprofile_set.last.id %}" role="button"
                            class="btn btn-primary btn-sm m-1"> Edit Profile</a>
                        {% else %}
                            <a href="{% url 'info:staff_profile_form' %}" role="button"
                            class="btn btn-primary btn-sm m-1"> Add Profile</a>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
            {% if staff.staffprofile_set.last %}
                <div class="d-flex flex-row">
                    <div class="container" style="padding: 16px; color: black;">
                        {% if staff.staffprofile_set.last.image %}
                            <img class="rounded float-start img-max-300-ar m-2" src="{{ staff.staffprofile_set.last.image.url }}">
                        {% endif %}
                        {{ staff.staffprofile_set.last.bio|safe }}
                    </div>
                </div>
            {% endif %}
        </div>
    {% endfor %}

{% endblock %}

wpa_project/info/templates/info/tmp.html
<!-- Include stylesheet -->
<link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">

<!-- Create the editor container -->
<div id="editor">
  <p>Hello World!</p>
  <p>Some initial <strong>bold</strong> text</p>
  <p><br></p>
</div>

<!-- Include the Quill library -->
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>

<!-- Initialize Quill editor -->
<script>
  var quill = new Quill('#editor', {
    theme: 'snow'
  });
</script>